import React from 'react';
import ReactDOM from 'react-dom/client';
import { ArrowRight, Bot, Check, Code2, Gauge, Globe2, Mail, Smartphone, Sparkles, Wrench, Zap } from 'lucide-react';
import accueil72Heures from './assets/72heures/Accueil.jpeg';
import besoins72Heures from './assets/72heures/Besoins.jpeg';
import stock72Heures from './assets/72heures/Stock.jpeg';
import './styles.css';

const email='lazuryte35@gmail.com';
const services=[
 {icon:<Globe2/>,title:'Sites internet',text:'Sites vitrines et expériences web modernes, rapides et adaptés à tous les écrans. Des contenus simples à faire évoluer sans dépendance inutile.'},
 {icon:<Code2/>,title:'Applications métier sur mesure',text:'Outils internes, interfaces, automatisations, API et applications sur mesure pour simplifier vos processus et gagner du temps.'},
 {icon:<Smartphone/>,title:'Applications mobiles',text:'Applications iOS et Android pensées pour un usage concret, de l’idée au prototype puis jusqu’au produit final.'}
];
const benefits=[['Rapide','L’IA accélère le prototypage et les tâches répétitives.',<Zap/>],['Coûts maîtrisés','Moins de temps perdu, davantage de valeur consacrée à votre besoin.',<Gauge/>],['Maintenable','Technologies standards, code structuré et solutions faciles à faire évoluer.',<Wrench/>],['Évolutif','Commencez simplement et enrichissez la solution au rythme de vos besoins.',<Sparkles/>]];

function HomePage(){return <>
<header className="nav"><a className="brand" href="#top"><span className="gem">L</span>LAZURYTE</a><nav><a href="#services">Services</a><a href="/creation-site-internet/">Création de site</a><a href="#approche">Approche</a><a href="#projet">72 Heures</a><a className="navCta" href={`mailto:${email}`}>Me contacter</a></nav></header>
<main id="top">
<section className="hero"><div className="orb one"/><div className="orb two"/><div className="heroInner"><div className="eyebrow"><Sparkles size={15}/> Développement web & mobile assisté par IA</div><h1>Vos idées.<br/><span>Des solutions concrètes.</span><br/>Plus vite.</h1><p>Lazuryte conçoit des <strong>sites web</strong>, des <strong>solutions métier</strong> et des <strong>applications mobiles</strong> sur mesure. Une approche moderne du développement pour transformer rapidement un besoin en produit utile, maintenable et évolutif.</p><div className="actions"><a className="primary" href={`mailto:${email}?subject=Parlons de mon projet`}>Parlons de votre projet <ArrowRight size={18}/></a><a className="secondary" href="#services">Découvrir Lazuryte</a></div><div className="trust"><span><Check/> Solutions sur mesure</span><span><Check/> IA intégrée au processus</span><span><Check/> Sans dépendance inutile</span></div></div></section>
<section id="services" className="section"><div className="sectionHead"><span>CE QUE JE PEUX CRÉER</span><h2>Du site vitrine à l’application complète.</h2><p>Une seule approche : comprendre le besoin, aller à l’essentiel et construire une solution propre qui pourra continuer à vivre après sa mise en ligne.</p></div><div className="cards">{services.map((s,i)=><article className="card" key={i}><div className="icon">{s.icon}</div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
<section id="approche" className="ai"><div className="aiInner"><div className="aiVisual"><div className="bot"><Bot size={54}/></div><div className="code">&lt; idée /&gt;<br/><span>→ prototype</span><br/>→ produit_</div></div><div className="aiCopy"><span className="tag">IA + EXPERTISE HUMAINE</span><h2>L’IA change la façon de développer.<br/>Autant en profiter.</h2><p>J’intègre l’intelligence artificielle directement dans mon processus de développement pour prototyper, analyser, tester et documenter plus rapidement.</p><p>Le but n’est pas de remplacer la réflexion : c’est de passer moins de temps sur les tâches répétitives et davantage sur <strong>votre besoin et la qualité du produit.</strong></p><div className="benefits">{benefits.map(([t,d,ic],i)=><div className="benefit" key={i}><div>{ic as React.ReactNode}</div><p><strong>{t as string}</strong><br/><span>{d as string}</span></p></div>)}</div></div></div></section>
<section className="method section"><div className="sectionHead"><span>UNE MÉTHODE SIMPLE</span><h2>De votre besoin à une solution qui fonctionne.</h2></div><div className="steps">{[['01','Échanger','Comprendre le problème, les utilisateurs et ce qui compte vraiment.'],['02','Prototyper','Rendre l’idée concrète rapidement pour valider la bonne direction.'],['03','Développer','Construire proprement, tester et ajuster au fil des retours.'],['04','Livrer & évoluer','Mettre en ligne une solution maintenable, prête à grandir.']].map((x,i)=><div className="step" key={i}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section id="projet" className="case"><div className="caseInner"><div className="caseCopy"><span className="tag">PROJET MOBILE • ÉTUDE DE CAS</span><h2>72 Heures</h2><h3>Préparer l’autonomie de sa famille, simplement.</h3><p>72 Heures est une application mobile conçue pour aider un foyer à préparer son autonomie en cas d’urgence : besoins essentiels, stocks à domicile, sac d’évacuation et suivi de la préparation.</p><p>Le projet illustre la démarche Lazuryte : partir d’un besoin réel, concevoir l’expérience, développer l’API et l’application mobile, puis itérer rapidement grâce à un workflow assisté par IA.</p><div className="tech"><span>React</span><span>TypeScript</span><span>Vite</span><span>MUI</span><span>Node.js / Fastify</span><span>MongoDB</span></div></div><div className="phones" aria-label="Captures de l’application 72 Heures"><div className="phone phoneNeeds"><div className="screen"><img src={besoins72Heures} alt="Écran Besoins de l’application 72 Heures, présentant les besoins essentiels du foyer"/></div></div><div className="phone phoneHome"><div className="screen"><img src={accueil72Heures} alt="Écran d’accueil de l’application 72 Heures, avec le suivi de préparation du foyer"/></div></div><div className="phone phoneStock"><div className="screen"><img src={stock72Heures} alt="Écran Stock de l’application 72 Heures, permettant de suivre les provisions"/></div></div></div></div></section>
<section className="maintain section"><div className="maintainBox"><div><span className="tag">VOUS RESTEZ MAÎTRE</span><h2>Des solutions faites pour durer.</h2></div><div><p>Un projet ne devrait pas devenir une boîte noire impossible à modifier. Les sites sont pensés pour être <strong>simples à administrer et à faire évoluer.</strong></p><p>Selon le besoin, vous pouvez gérer vous-même vos contenus. Et côté technique, je privilégie un code structuré, documenté et des technologies standards : votre projet reste compréhensible et reprenable.</p></div></div></section>
<section className="contact"><div><span>UN PROJET ? UNE IDÉE ?</span><h2>Construisons quelque chose d’utile.</h2><p>Interlocuteur direct basé près de Vitré, j’accompagne les projets à Rennes et partout en Bretagne, ainsi qu’à distance. Expliquez-moi simplement votre besoin : nous verrons ensemble la solution la plus adaptée, sans jargon inutile.</p><a className="primary" href={`mailto:${email}?subject=Mon projet avec Lazuryte`}><Mail size={18}/> {email}</a></div></section>
</main><footer><a className="brand" href="#top"><span className="gem">L</span>LAZURYTE</a><span>Sites web • Solutions métier • Applications mobiles</span><small>© {new Date().getFullYear()} Lazuryte</small></footer>
</>}

function CreationSiteInternetPage(){return <>
<header className="nav"><a className="brand" href="/"><span className="gem">L</span>LAZURYTE</a><nav><a href="/#services">Services</a><a href="#offres">Offres</a><a href="#deroulement">Déroulement</a><a className="navCta" href={`mailto:${email}?subject=Création de site internet`}>Me contacter</a></nav></header>
<main>
<section className="hero pageHero"><div className="orb one"/><div className="orb two"/><div className="heroInner"><div className="eyebrow"><Globe2 size={15}/> Création et refonte de sites internet</div><h1>Création de sites internet <span>à Vitré et Rennes</span></h1><p>Un site clair, rapide et pensé pour votre activité. Lazuryte conçoit ou refond votre présence en ligne avec une approche directe, un code maintenable et une solution facile à faire évoluer.</p><div className="actions"><a className="primary" href={`mailto:${email}?subject=Création de site internet`}>Parlons de votre projet <ArrowRight size={18}/></a><a className="secondary" href="#offres">Découvrir les offres</a></div><div className="trust"><span><Check/> Design adapté à votre besoin</span><span><Check/> Performance et simplicité</span><span><Check/> Évolutif dans le temps</span></div></div></section>
<section id="offres" className="section"><div className="sectionHead"><span>UNE PRÉSENCE EN LIGNE QUI VOUS RESSEMBLE</span><h2>Le bon site, au bon niveau de complexité.</h2><p>Chaque projet commence par vos objectifs : présenter votre activité, générer des contacts ou proposer une expérience plus spécifique.</p></div><div className="cards"><article className="card"><div className="icon"><Globe2/></div><h3>Site vitrine</h3><p>Une présentation professionnelle de votre activité, de vos services et de vos réalisations, conçue pour inspirer confiance et faciliter la prise de contact.</p></article><article className="card"><div className="icon"><Wrench/></div><h3>Refonte de site</h3><p>Un site existant modernisé pour gagner en clarté, en rapidité, en confort mobile et en facilité de mise à jour.</p></article><article className="card"><div className="icon"><Code2/></div><h3>Site sur mesure</h3><p>Des fonctionnalités adaptées à votre métier : espace client, connexion à vos outils, formulaires avancés ou parcours spécifiques.</p></article></div></section>
<section className="ai"><div className="aiInner"><div className="aiVisual"><div className="bot"><Bot size={54}/></div><div className="code">&lt; idée /&gt;<br/><span>→ prototype</span><br/>→ site_</div></div><div className="aiCopy"><span className="tag">IA + EXPERTISE HUMAINE</span><h2>Un développement moderne, assisté par l’IA.</h2><p>L’intelligence artificielle accélère la recherche, le prototypage et certaines tâches de développement. Elle permet d’avancer plus vite, sans sacrifier la qualité.</p><p>La conception, les choix utiles à votre activité et le contrôle du résultat restent humains. Le code est structuré et maintenable pour que votre site puisse évoluer sereinement.</p><div className="benefits"><div className="benefit"><div><Zap/></div><p><strong>Plus rapide</strong><br/><span>Un prototype concret plus tôt.</span></p></div><div className="benefit"><div><Wrench/></div><p><strong>Maintenable</strong><br/><span>Une base technique claire et durable.</span></p></div></div></div></div></section>
<section id="deroulement" className="method section"><div className="sectionHead"><span>UN DÉROULEMENT SIMPLE</span><h2>Du besoin à la mise en ligne, puis aux évolutions.</h2></div><div className="steps">{[['01','Comprendre le besoin','Vos objectifs, vos utilisateurs et les contenus essentiels.'],['02','Proposer & prototyper','Une direction concrète pour valider l’expérience avant de développer.'],['03','Développer','Un site performant, responsive et soigneusement testé.'],['04','Mettre en ligne','Une publication maîtrisée, avec les bases pour bien démarrer.'],['05','Faire évoluer','Des améliorations possibles au rythme de votre activité.']].map((x,i)=><div className="step" key={i}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section className="maintain section"><div className="maintainBox"><div><span className="tag">PROXIMITÉ, SANS LIMITES</span><h2>À Vitré, près de Rennes, et à distance.</h2></div><div><p>Basé à Vitré, Lazuryte accompagne les entreprises, indépendants et projets locaux à Rennes et partout en Bretagne.</p><p>La collaboration à distance est tout aussi simple : des échanges directs, des étapes claires et un interlocuteur unique tout au long du projet.</p></div></div></section>
<section className="contact"><div><span>VOTRE SITE, VOTRE PROJET</span><h2>Faisons de votre présence en ligne un vrai outil.</h2><p>Décrivez votre projet de création ou de refonte de site internet. Nous définirons ensemble une solution utile, adaptée et prête à évoluer.</p><a className="primary" href={`mailto:${email}?subject=Création de site internet`}><Mail size={18}/> {email}</a></div></section>
</main><footer><a className="brand" href="/"><span className="gem">L</span>LAZURYTE</a><span>Sites web • Solutions métier • Applications mobiles</span><small>© {new Date().getFullYear()} Lazuryte</small></footer>
</>}

const isCreationSiteInternetPage=window.location.pathname.replace(/\/$/,'')==='/creation-site-internet';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{isCreationSiteInternetPage?<CreationSiteInternetPage/>:<HomePage/>}</React.StrictMode>);
